name: Trigger remote workflow (GitHub/Gitea)
description: Trigger a workflow in another repository on GitHub or Gitea (same or different instance).
author: ravenwolf.org
branding:
  icon: 'play'
  color: 'blue'

inputs:
  repo:
    description: >
      Target repository. Formats supported:
      - owner/repo
      - https://github.com/owner/repo
      - https://gitea.example.com/owner/repo
    required: false
  workflow-name:
    description: >
      Workflow name to dispatch. This is the top-level `name:` field in the workflow YAML file.
      If the workflow has no `name:` field, the filename (without extension) is used as fallback.
      NOT the job name or step name.
      Example: if your workflow has `name: CI/CD Pipeline`, use `workflow-name: CI/CD Pipeline`.
      Example: if your workflow file is `build.yml` with no name field, use `workflow-name: build`.
    required: true
    deprecationMessage: 'Use workflow-name instead of workflowName'
  ref:
    description: Git ref to run the workflow on (branch/tag/SHA).
    required: false
    default: main
  base-url:
    description: >
      Base URL for the target instance (GitHub or Gitea).
      Auto-inferred from repo URL or runner env (GITHUB_SERVER_URL / GITEA_SERVER_URL).
      Override if inference is incorrect.
    required: false
    deprecationMessage: 'Use base-url instead of baseUrl'
  token:
    description: >
      API token for the target instance (GitHub or Gitea). If omitted, falls back to runner environment token (GITHUB_TOKEN or GITEA_TOKEN).
      Token must have permission to read workflows and dispatch runs in the target repo.
    required: false
  inputs:
    description: Optional JSON object string of inputs for the workflow dispatch.
    required: false
  skip-certificate-check:
    description: Skip TLS certificate verification for API calls (self-hosted instances).
    required: false
    default: "false"
    deprecationMessage: 'Use skip-certificate-check instead of skipCertificateCheck'
  verbose:
    description: Enable verbose logging (HTTP attempts, endpoint discovery, response snippets). Also enabled when ACTIONS_STEP_DEBUG=true.
    required: false
    default: "false"

runs:
  using: node20
  main: dist/index.js


